### PR TITLE
docs: Update gravity extention docs

### PR DESCRIPTION
**Pull request by crocket63**
## Summary

Gear gravity extension process will get reversible in new pr #7189, this updates the docs accordingly.

### Location

Discord username (if different from GitHub):

### CODE REVIEW

**Comment by Valastiri** [comment]
Reference PR:
- https://github.com/flybywiresim/a32nx/pull/7189

**Comment by crocket63** [comment]
This is merged on dev so good to go

**Comment by Valastiri** [comment]
check build

**Comment by Valastiri** [comment]
lgtm thanks davy

**Pull request merged**
