### PR TITLE
fix: update discord usernames to new format

### LINKED ISSUE #841: Wrong discord usernames
After the new username update, at least straks', oim's and benw's usernames need changing in [https://docs.flybywiresim.com/dev-corner/development-projects/discord-bot/](https://docs.flybywiresim.com/dev-corner/development-projects/discord-bot/), some other usernames might need changing in other places as well, not sure.

### PR DESCRIPTION
**Pull request by Valastiri**
closes: #841

## Summary
Based on Discord's new usernames format updated references across documentation if applicable.

### Location
- docs/dev-corner/development-projects/discord-bot.md
- docs/dev-corner/development-projects/documentation.md

Discord username (if different from GitHub):
 valastiri

### CODE REVIEW

**Comment by Sleinmaster** [comment]
@Valastiri do you want to do the same change here? https://docs.flybywiresim.com/dev-corner/development-projects/documentation/?h=doc

**Comment by Valastiri** [comment]
> @Valastiri do you want to do the same change here? [docs.flybywiresim.com/dev-corner/development-projects/documentation/?h=doc](https://docs.flybywiresim.com/dev-corner/development-projects/documentation/?h=doc)

Forgot about the usernames on that page -- i'll update PR and that page as well

**Comment by Valastiri** [comment]
@Sleinmaster i left your username the same since that's what Discord reported -- let me know if that's intended for you

**Comment by Sleinmaster** [comment]
> @Sleinmaster i left your username the same since that's what Discord reported -- let me know if that's intended for you

The rollout just didn't get to me yet, I guess because I'm relatively new on discord. I can correct it, when it gets to me.

**Comment by Valastiri** [comment]
> > @Sleinmaster i left your username the same since that's what Discord reported -- let me know if that's intended for you
> 
> The rollout just didn't get to me yet, I guess because I'm relatively new on discord. I can correct it, when it gets to me.

Sounds good! Forgot it was a rollout will merge and we can update at a later time thanks!

**Pull request merged**
