### PR TITLE
docs: wind request simbrief integration

### LINKED ISSUE #561: add wind requests feature
Possibly to be included in the beginner guide rather than a separate feature.

Planning to be part of the MCDU section as it's related and good practice to have the wind requests in when configuring the aircraft.

Reference PR:
- https://github.com/flybywiresim/a32nx/pull/7158

### PR DESCRIPTION
**Pull request by USA-RedDragon**
Relates #561

## Summary
Started documenting the wind request feature in the Simbrief Integration page. I figure it should be added to the Beginner's Guide under Preparing the MCDU, but I'm not sure which step under DIFSRIP the wind request would typically occur. I would appreciate input on this.

### Location
`fbw-a32nx/feature-guides/simbrief` or `fbw-a32nx/feature-guides/simbrief/#initialize-flight-plan` specifically

Discord username (if different from GitHub): USA-RedDragon#1776

### CODE REVIEW

**Comment by USA-RedDragon** [comment]
I wasn't sure how to get the MCDU pictures. The default MCDU view in MSFS has it at a perspective angle, so I'm seemingly not able to get the nice squared screenshot matching the ones already on the page.

**Comment by frankkopp** [comment]
> I wasn't sure how to get the MCDU pictures. The default MCDU view in MSFS has it at a perspective angle, so I'm seemingly not able to get the nice squared screenshot matching the ones already on the page.

Takes some camera positioning - not hard use arrow keys and num pad / and * - also use mouse to make sure the camera is looking straight down on the MCDU. Make sure to match the lighting - usually I do these at 12am zulu with Clear weather preset - might need to play with time a bit to avoid shadows.

**Comment by USA-RedDragon** [comment]
Github needs a :thankyou: emoji bad so I don't have to generate as much noise just to say thanks for the help.

**Comment by Valastiri** [comment]
Hello :) Any update on this PR?

**Comment by frankkopp** [comment]
Also covered here now: 
https://docs-git-fork-frankkopp-briefing-mcdu-flybywire.vercel.app/pilots-corner/a32nx-briefing/mcdu/f-pln/#wind-page

But would be great to have this addition in - @USA-RedDragon are you planning to complete this or should we take over?

**Comment by frankkopp** [comment]
@USA-RedDragon 

@Valastiri We should take over and finish this.

**Comment by Valastiri** [comment]
Will be closing this and taking it over. I'll add co-authorship credits to the new PR.

**Comment by Valastiri** [comment]
Closing this PR since there has been no contact from the original author. Re-opened in #690 to takeover work.

**Pull request closed without merging**
