### PR TITLE
docs: fbw rebrand

### PR DESCRIPTION
**Pull request by Valastiri**
## Summary
To facilitate rebranding efforts this PR should adhere to our new guidelines, color palette, and typography. 

- New Hero Image
		- Credit: Maple#3904 FBW Media Team
- Header font = Manrope
- General text = Inter
- Changes to the readability of the reported-issues page
- CSS styles are updated
- Added border to announcement bar (suggested by Kevin)
- Fixed button hover state text color to black
- H1 `font-weight: 550px` down from 600.

A cleanup of the styles and rework of the reported issues is courtesy of @GhostEagle68: 
- PR #341 

Courtesy Link: [Staging Preview](https://docs-git-fbw-rebrand-flybywire.vercel.app/)

## To do

- [x] Check table colors + navigation hover state
- [x] Remove unused pngs

Discord username (if different from GitHub): Valastiri#8902

### CODE REVIEW

**Review by FoxtrotSierra6829 — COMMENTED** [review]
The newly added `new-fbw-tail.png` does not seem to be in use. Also, we could delete the old logos that aren't in use anymore. That affects `FBW-Logo-WHITE.png`, `FBW-Logo.png`, `FBW-Square-White.png` and  `FBW-Tail.png`. And as we're already onto it, we should rename the newly added `fbw_logo-n.png` properly👀

**Review by frankkopp — APPROVED** [review]
image
Is this mouse over color intentional?

Also do these colors belong together:
image

All in all the changes make it better to read in regards to contrast.
Design is also a matter of taste - I think it is a bit colorful and I don't like all color combinations (see above).

Otherwise LGTM - the improvement in clarity and readability is good.

**Comment by Valastiri** [comment]
Oh actually I'll have to look into that -- not the best hover state color. 

Also I don't think I touched the tables I'll have to double-check that as well

**Comment by Valastiri** [comment]
> The newly added `new-fbw-tail.png` does not seem to be in use. Also, we could delete the old logos that aren't in use anymore. That affects `FBW-Logo-WHITE.png`, `FBW-Logo.png`, `FBW-Square-White.png` and `FBW-Tail.png`. And as we're already onto it, we should rename the newly added `fbw_logo-n.png` properly👀

Ah yea I think the `new-fbw-tail.png` might've been from the reference PR. I'll clean it up today.

**Comment by Valastiri** [comment]
Okay cleanup's done and checked the additional styling -- additionally the font import should be working now hopefully.

**Comment by frankkopp** [comment]
I went through it again and couldn't find any issues. 
LGTM

**Comment by Valastiri** [comment]
check build

**Comment by Valastiri** [comment]
check build

**Comment by Valastiri** [comment]
Weird why the test build won't work :/

**Comment by Valastiri** [comment]
check build

**Comment by Valastiri** [comment]
rebased onto primary

**Comment by Valastiri** [comment]
Rebased in prep for publication of:

- https://github.com/flybywiresim/website/pull/388

**Comment by Valastiri** [comment]
check build

**Pull request merged**
