### PR TITLE
Docs: TCA,TWCS,Honeycomb and Keyboard Screenshots update

### LINKED ISSUE #729: Update flyPad 2 screenshots on calibration guide
Throttle calibration page still has flyPad 2 screenshots
<https://docs.flybywiresim.com/fbw-a32nx/feature-guides/flypados3/throttle-calibration/#thrustmaster-tca-throttle>
image

### PR DESCRIPTION
**Pull request by Luz5020**
fixes #729
## Summary

Updates all Screenshots in the TCA section of the calibration guide to the EFB 3 images
### Location

https://docs.flybywiresim.com/fbw-a32nx/feature-guides/flypados3/throttle-calibration/#thrustmaster-tca-throttle

Discord username (if different from GitHub):

### CODE REVIEW

**Comment by Luz5020** [comment]
Just noticed the Issue is not only the TCA section but also the TWCS and Honeycomb, I overlooked those because the issue had a screenshot for the TCA only. Can't take any screenshots right now, and I don't even have a throttle :( . So lmk if this can be merged or if the other images need updating too, I could replace the images, and I think there's a way to influence the EFB into showing the necessary display. So I might be able to take the shots even without a throttle

**Comment by Valastiri** [comment]
The quality of the image seems rather pixelated and bad. Over compression? 

I say this also because we have a lightbox so clicking on them makes it quite obvious.

**Comment by Luz5020** [comment]
Used the high compression as usual, I can try with less compression if it's okay in terms of file size

**Comment by Valastiri** [comment]
> Used the high compression as usual, I can try with less compression if it's okay in terms of file size

Compression shouldn't usually alter the quality even in Lossy. All of our images are compressed and usually are not grainy by any means. (Try a sample upload as a comment or via Discord just to double check if you need.) All the images are fine tho beyond that.

**Comment by Luz5020** [comment]
Okay, seems the switch to pngs helped, at least on my end. If the quality is good on all ends I'll go ahead and remove the jpg files. another thing, I think I can take the necessary images to update the rest of the page to flypad3. If possible I'd like to keep this PR active as converting to draft with GH seems to not work that well.

**Comment by Valastiri** [comment]
looks great thanks!

**Pull request merged**
