### PR TITLE
feat(simbridge): Remote SimBridge documentation 

### LINKED ISSUE #739: Update for Remote Simbridge Host
See PR: https://github.com/flybywiresim/a32nx/pull/7708

Now simbridge can be used remotely from another computer on your local network, settings page documentation should be updated.

### PR DESCRIPTION
**Pull request by alepouna**
Fixes #739

## Summary

Adds a new feature to the list of feature guides on SimBridge's main page.

Page describes how to utilize SimBridge on an external machine and any caveats / troubleshooting required.

### Location

- docs/simbridge/simbridge-feature-guides/remote-simbridge.md

Discord username (if different from GitHub): Alepouna🌙#9824

### To Do 
- [ ] Troubleshooting 
   - [ ] Port problems
 
- [ ] Known Issues
   - [ ] Running on a different network 
   - [ ] Running with more than one planes connected

- [ ] Images

### CODE REVIEW

**Comment by alepouna** [comment]
Page can be found here: https://docs-41z4kekki-flybywire.vercel.app/simbridge/simbridge-feature-guides/remote-simbridge/

**Comment by alepouna** [comment]
Maintaining draft/on hold status as there is a pending update for SimBrief/a32nx that will essentially disable that feature (at least for the terrain ND), will work on this again after that :)

**Comment by JasonO99** [comment]
@auroraisluna is this documentation still awaiting an update to the aircraft?

**Comment by alepouna** [comment]
> @auroraisluna is this documentation still awaiting an update to the aircraft?

Yes, remote simbridge is not a feature anymore, at least for TR ND. If you want to write documentation as such, you will need to create something that messes with the SimConnect files.

**Comment by JasonO99** [comment]
> 

No probs! I did think the hold up was with the Terrain ND. It still has the remote MCDU functionality, right? It indeed would be confusing to document it when it's only partially working though so makes sense to remain on hold.

**Pull request closed without merging**
