### PR TITLE
docs: A32NX Briefing - ND

### PR DESCRIPTION
**Pull request by Awemeter**
## Summary

Create the ND section of the a32nx-briefing

Sections:

- [ ] ND Overview

<br>

- Pages:
- [ ] Course
- [ ] Selected Heading
- [ ] Other Messages
- [ ] Chronometer
- [ ] Navigation Receivers

### Location

/pilots-corner/a32nx-briefing/

Discord username (if different from GitHub): Awemeter#3110

### CODE REVIEW

**Comment by frankkopp** [comment]
@Awemeter are you planning on continue working on this?

**Comment by Awemeter** [comment]
> @Awemeter are you planning on continue working on this?

Yes, probably this weekend. Something that I am trying to figure out is showing all symbols / data blocks at once.

**Comment by frankkopp** [comment]
> > @Awemeter are you planning on continue working on this?
> 
> Yes, probably this weekend. Something that I am trying to figure out is showing all symbols / data blocks at once.

Yea - not easy - even mocking it with the code would be a lot of work I guess. Not even the FCOM with its schematic diagrams does this though as it is probably too much.

**Comment by Awemeter** [comment]
> > > @Awemeter are you planning on continue working on this?
> > 
> > 
> > Yes, probably this weekend. Something that I am trying to figure out is showing all symbols / data blocks at once.
> 
> Yea - not easy - even mocking it with the code would be a lot of work I guess. Not even the FCOM with its schematic diagrams does this though as it is probably too much.

Do you have any suggestions on what I should do?

**Comment by frankkopp** [comment]
> > > > @Awemeter are you planning on continue working on this?
> > > 
> > > 
> > > Yes, probably this weekend. Something that I am trying to figure out is showing all symbols / data blocks at once.
> > 
> > 
> > Yea - not easy - even mocking it with the code would be a lot of work I guess. Not even the FCOM with its schematic diagrams does this though as it is probably too much.
> 
> Do you have any suggestions on what I should do?

Some ideas:
- have sections for of all modes ROSE LS, ROSE VOR, ROSE NAV, ARC, PLAN incl. screenshots
- Terrain section & screenshots 
- maybe use a technique as in this image: https://docs.flybywiresim.com/pilots-corner/a32nx-briefing/pfd/flags-messages/#description
- Maybe EFIS section explaining all controls influencing the ND

As a general tip: Always start with the structure (sections/chapters) by writing all planned headlines and maybe a short summary what the section will be about and what screenshots/illustrations you will need. This way you get a good overview if the docs page(s) will work and also a nice todo-list.

Example from the FCOM (quite ugly but works well esp. with nicer illustrations)
image
image

**Comment by frankkopp** [comment]
@Awemeter would you mind if I take over or create a new PR for this? I would like this to move forward as it is the last major display not documented.

**Comment by Valastiri** [comment]
Outdated

**Pull request closed without merging**
