### PR TITLE
feat: initial implementation of OG + twitter cards

### PR DESCRIPTION
**Pull request by Valastiri**
- Added configuration to overrides main.html to support Open Graph meta + Twitter Cards.
- Added initial design of card graphic provided by LeDerpLegend#0109 from Marketing Team

Using a new branch `meta-seo` to roll out meta on headers for one large impelmentation. Will first check how the implementaton works using Vercel and if it works as intended will merge into primary instead and work accordingly.

To-do:

- [ ] Revert https://github.com/flybywiresim/docs/pull/124/commits/f477fde875de09a0b782d8c0321471b6ef784893 before merging

### CODE REVIEW

**Comment by Benjozork** [comment]
can you add a screenshot of the preview to the PR body ?

**Comment by Valastiri** [comment]
@Benjozork 

Ideally this is how it should look:
image

image

Ignore the domain, it's a localhost tunnel.

**Comment by Benjozork** [comment]
Any updates on this ?

**Comment by Valastiri** [comment]
@Benjozork I may need to double-check the usability of this after the redesign of docs as we are utilizing a new directory structure. I'll test it this week.

Other consideration is to wait for mkdocs-material to roll in their [prebuilt embeds](https://squidfunk.github.io/mkdocs-material/setup/setting-up-social-cards/) as they are similar to how GitHub does theirs. (Currently insiders only 'experimental')

**Pull request closed without merging**
